var myTable="<table>";
myTable += "<tr>";
myTable += "<td>"+"일"+"</td>";
myTable += "<td>"+"월"+"</td>";
myTable += "<td>"+"화"+"</td>";
myTable += "<td>"+"수"+"</td>";
myTable += "<td>"+"목"+"</td>";
myTable += "<td>"+"금"+"</td>";
myTable += "<td>"+"토"+"</td>";
myTable += "</tr>";
myTable +="</table>";
document.write(myTable);